#!/bin/bash

gcloud compute firewall-rules create allow-http --description "allowing http." --allow tcp:80

gcloud compute firewall-rules create allow-https --description "allowing https." --allow tcp:443

gcloud compute firewall-rules create allow-ldap --description "allowing LDAP." --allow tcp:636

gcloud compute instances create ldap-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Gcloud/ldap-s.bash

gcloud compute instances create nfs-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Gcloud/nfs-s.bash

gcloud compute instances create postgres-test --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Gcloud/postgres.bash

sleep 1m

Ippos:$(gcloud compute instances list | grep postgres-test | awk '{print $4}')

gcloud compute instances create django-test --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Gcloud/django.bash

Ipl=$(gcloud compute instances list | grep ldap-server | awk '{print $4}')

Ipnfs=$(gcloud compute instances list | grep nfs-server | awk '{print $4}')

sed -i -e "17s,.*,sed -i \"30s\,uri ldapi:///\,uri ldaps://$Ipl/\,g\" \/etc\/ldap.conf,g" /home/yojetoga/Gcloud/client.bash

sed -i "42s/.*/Ipserver=$Ipnfs/" /home/yojetoga/Gcloud/client.bash

gcloud compute instances create client --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Gcloud/client.bas


