#!/bin/bash

#firewalls rules. adding permissions to the instances
gcloud compute firewall-rules create allow-http --description "allowing http." --allow tcp:80
gcloud compute firewall-rules create allow-https --description "allowing https." --allow tcp:443
gcloud compute firewall-rules create allow-ldap --description "allowing LDAP." --allow tcp:636

#creating an instances with LDAP server
gcloud compute instances create ldap-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/ldap-s.bash

#creating an instances with NFS server
gcloud compute instances create nfs-server --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/nfs-s.bash

#variable with the name of the first postgres server
pos1=test

#adding the name to the script postgres server
sed -i "4s/.*/Napostgres=$pos1/" /home/yojetoga/Servers/Gcloud/postgres.bash

#creating an instance with Postgres server
gcloud compute instances create postgres-test --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/postgres.bash

#giving a minute to update the stage of the postgres server
sleep 1m

#variable with the IP of the first postgres server
Ippos=$(gcloud compute instances list | grep postgres-test | awk '{print $4}')

#adding the IP to the script of django server
sed -i "3s/.*/Ippost=$Ippos/" /home/yojetoga/Servers/Gcloud/django.bash

#creating an instance with Django server
gcloud compute instances create django-test --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/django.bash

#variable with the name of the second postgres server
pos2=staging

#adding the name to the script of the postgres server
sed -i "4s/.*/Napostgres=$pos2/" /home/yojetoga/Servers/Gcloud/postgres.bash

#creating an instance with Postgres server
gcloud compute instances create postgres-staging --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/postgres.bash

#giving a minute to update the stage of the postgres server
sleep 1m

#variable with the IP of the second postgres server
Ippos=$(gcloud compute instances list | grep postgres-staging | awk '{print $4}')

#adding the IP to the script of the django server
sed -i "3s/.*/Ippost=$Ippos/" /home/yojetoga/Servers/Gcloud/django.bash

#creating an instance with Django server
gcloud compute instances create django-staging --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/django.bash

#variable with the name of the third postgres server
pos3=production

#adding the name to the script of the postgres server
sed -i "4s/.*/Napostgres=$pos3/" /home/yojetoga/Servers/Gcloud/postgres.bash

#creating an instance with Postgres sever
gcloud compute instances create postgres-production --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/postgres.bash

#givin 1 minute to update the stage of postgres server
sleep 1m

#variable with the IP of the third postgres server
Ippos=$(gcloud compute instances list | grep postgres-production | awk '{print $4}')

#adding the IP to the script of the django server
sed -i "3s/.*/Ippost=$Ippos/" /home/yojetoga/Servers/Gcloud/django.bash

#creating an instances with Django server
gcloud compute instances create django-production --image-family centos-7 --image-project centos-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/django.bash

#variable with the IP of the LDAP server
Ipl=$(gcloud compute instances list | grep ldap-server | awk '{print $4}')

#variable with the IP of the NFS server
Ipnfs=$(gcloud compute instances list | grep nfs-server | awk '{print $4}')

#adding the IP of the LDAP server to the script of the client
sed -i -e "17s,.*,sed -i \"30s\,uri ldapi:///\,uri ldaps://$Ipl/\,g\" \/etc\/ldap.conf,g" /home/yojetoga/Servers/Gcloud/client.bash

#adding the IP of the NFS server to the script of the client
sed -i "45s/.*/Ipserver=$Ipnfs/" /home/yojetoga/Servers/Gcloud/client.bash

#creating an instance as a client
gcloud compute instances create client --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud --machine-type f1-micro --metadata-from-file startup-script=/home/yojetoga/Servers/Gcloud/client.bash

